name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -f src/Portfolio.Authorization.Service/Dockerfile -t portfolio-auth-service .

    - name: Run Docker container
      run: |
        # Stopping any previous instance of the container (optional)
        docker stop portfolio-auth-service-container || true
        docker rm portfolio-auth-service-container || true

        # Running the Docker image
        docker run -d --name portfolio-auth-service-container -p 35010:5000 portfolio-auth-service